### ISSUE TITLE
Admin Configurations

### ISSUE THREAD

**Issue by enkob** [Kodluyoruz/discord-register-bot#4]
Discord sunucusunun bir yöneticisi olarak, kullanıcı kaydını ve erişimini yönetmek için Discord Kayıt Botunun ayarlarını ve özelliklerini yapılandırabilmek istiyorum.

## todo

- [ ]  register channel -- Botun kurulumunun 2. adımında kullanıcı "kod ile kayıt odası ayarı" butonuna tıkladığında moderatörün, kullanıcıların hangi kanalda kodlarını girerek kayıt olacakları odayı seçeceği odaların listesi dropdown şeklinde açılır. odayı seçip kuruluma başlar.
- [ ]  /logChannel  -- Discord sohbetine /LogChannel" komutunu yazdığımda, bot komutun yanında bir prompt belirtip yazılan kanalı log kanalı yapar.
- [ ]  /userList  -- Discord sohbetine "/userList" Komutu yazdığımda, bot Discord sunucusundaki kişileri listeler.
- [ ] /role --  Discord sohbetine "/role Komutu yazdığımda, bot ardışık iki promt çıkarıri ilk prompt isim, ikinci prompt rol için açılır. Yazılan isime yazılan rolu atar
- [ ] /customPrefix 
- [ ] /removeRole -- Discord sohbetine "/removeRole" Komutu yazdığımda, bot ardışık iki promt çıkarıri ilk prompt isim, ikinci prompt rol için açılır. Yazılan isimden yazılan rolu kaldırır.
- [ ] /isUserCanSignUp 
- [ ] /isRegisterMessagesBeDeleted 
- [ ] /lastRegisters -- Discord sohbetine "/removeRole" Komutu yazdığımda, bot kayıt olan son 10 kişinin listesini verir.
- [ ] /setBackUp 
- [ ] /backUp

**Comment by enkob** [comment]
Kurulum PNGs

![Image](https://user-images.githubusercontent.com/130500728/234669784-5f613f2a-d2f3-4c46-9a4a-f2363fcf6a12.png)

![Image](https://user-images.githubusercontent.com/130500728/234669428-d98a39dd-3803-449c-bfc3-7029d63191bb.png)

![Image](https://user-images.githubusercontent.com/130500728/234669427-b19dd9cb-4bd8-461f-80a0-cf5848143193.png)

**Comment by azateser** [comment]
İlk Aşamada Olacaklar için Tüm Tasarım: https://www.figma.com/file/qNPjC3RgbF5iyFTZQzHVjS/Discord-Register-Bot-UX-(KODLUYORUZ-AKK)?node-id=64%3A1577&t=aQcjyClQ9mZrgyyt-1

Kayıt Ayar Ekranı İçin: https://www.figma.com/file/qNPjC3RgbF5iyFTZQzHVjS/Discord-Register-Bot-UX-(KODLUYORUZ-AKK)?node-id=64%3A2269&t=aQcjyClQ9mZrgyyt-1



![Image](https://user-images.githubusercontent.com/16418661/234705448-6c655137-cc31-43c4-a03f-efe9deb400f3.png)



![Image](https://user-images.githubusercontent.com/16418661/234705457-d8ffbcf5-6740-421a-932c-557760771199.png)
